server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_schema
    username: root
    password: 520.LUhaiDA
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
reggie:
  path: /Users/luhaida/Documents/Project/reggie

